version: "3.8"

services: 
  server:
    image: 'nginx:stable-alpine'
    ports: 
      - '8000:80'
    volumes: 
      - ./src:/var/www/html
      # merge our conf file into the overall conf file setup in the nginx image:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  # the php container's service name must be the same as in nginx.conf -> fastcgi_pass php
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      # make source code available to the php container:
      # no :ro because laravel will generate some files:
      - ./src:/var/www/html:delegated
  mysql:
    image: mysql:5.7
    # set the env vars required by the image:
    env_file: 
      - ./env/mysql.env 
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      # make source code available to the composer container:
      - ./src:/var/www/html
  # artisan:
  # npm: